using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DynamicWindows
{
    public class HelpWindows
    {
        public string RPHelp { get; } = "The PROFILE ROLEPLAY setting allows you to share your intrest in roleplaying with other players.  This option is not toggleable and will always be shown when somebody views your profile.\n\nPROFILE /SET {ROLEPLAY | RP}  {option # | text}\nExample: PROFILE /SET ROLEPLAY 1\n         PROFILE /SET RP HEAVY\n\n1.  HEAVY - This setting will indicate that you wish to remain in an environment that is as immersive as possible and you would prefer that even veiled references to things outside of the game's environment and setting or openly discussing things such as mechanics be avoided. This is for people with a strong grasp of the game's lore and setting and for which remaining in-character and actively pursuing events and roleplaying opportunities with others is a top priority.\n\n2.  MEDIUM - This setting will indicate that you enjoy roleplaying most of the time and that it is a regular consideration in your interaction with others. This is appropriate for people who guide their interactions with others according to their character's personality, actively pursue in events and participate in roleplaying with others, but still feel comfortable talking about mechanics and ranks or making veiled references to things outside of the game, such as the boards, lag, or IM clients.\n\n3.  LIGHT - This setting indicates that you enjoy casual roleplay but do not specifically set out to do so. This is ideal for people willing to interact with others in an in-character fashion and who enjoy socializing from time to time, but whom for participation in events and pursuing roleplay with others is a relatively low priority. This setting is also appropriate for new players who are interested in roleplay but are not familiar with the environment and the game's setting and are unsure of where they currently fit in.\n\n4.  NONE (Not Really My Thing) - This setting indicates that you do not actively engage in roleplay nor do you wish for others to attempt to roleplay with you. Note that even those with this flag must respect the game environment and attempt to remain in-genre and avoid discussing blatantly out of character references within the game. This setting is appropriate for people who consider themselves casual gamers who just want to log on and play the game, or who are only interested in training and advancement with little to no in-character socialization.";
        
        public string PVPHelp { get; } = "The PROFILE PVP setting allows you to share your intrest in PvP situations with other players.  These settings are GUIDELINES, not hard and fast locked in settings.  They can be changed, but only on an infrequent basis.\n\n**********************************************************************\n**********************************************************************\nWhen you change this setting, be sure you are setting it to the option\nthat you want, because you will not be able to change it for the next\n48 hours (real life time).\n**********************************************************************\n**********************************************************************\n\nPROFILE /SET PVP {option # | text}\nExample:  PROFILE /SET PVP 1\n          PROFILE /SET PVP OPEN\n\n1.  OPEN - This setting indicates that you welcome any conflict with any person at any time. This is a dangerous setting and should not be chosen lightly, as it will leave you open to random attacks without any recourse available from a GM. Basically, if you have this set, you are on your own when it comes to PVP and you accept that completely.\n\n2.  GUARDED - This setting indicates that you are open to PVP conflicts, provided you're aware they're coming. This option is good for people who enjoy PVP and enjoy \"GM-less\" conflict, as long as all parties involved are consenting and have agreed beforehand what's going to happen.\n\n3.  CLOSED - This setting indicates that you prefer to do everything you can to avoid PVP. Please note that this setting does not PROTECT you from PVP, it merely states that you're not generally interested in participating. If you choose to do things that cause bad feelings or ill will, however, you may get involved in PVP whether you like it or not.";
        
        public string SPOUSEHelp { get; } = "The PROFILE SPOUSE setting allows you to display information about your spouse, or lack thereof, with other players.  These settings are:\nPROFILE /SET SPOUSE {option # | text}\nExample:  PROFILE /SET SPOUSE 1\n          PROFILE /SET SPOUSE BONDED\n\n1.  UNINTERESTED - Select this option if you do not have a spouse and do not care to have one.\n\n2.  SINGLE - Select this option if you do not have a spouse and want to let the rest of Elanthia know that you are an elligble bachelor/bachelorette.\n\n3.  BONDED - Select this option if you have a spouse and don't want the rest of Elanthia to know who it is.\n\n4.  BONDEDTO  - Select this option if you have a spouse and want the rest of Elanthia to know who it is. **NOTE** If you set your PvP Stance to OPEN this option will be shown regardless of what your SPOUSE setting is.\n\n5.  NOINFO - Select this option if you don't want to display anything related to spouses.";
    }
}
